### ISSUE TITLE
違うステージのimportがおかしい

### ISSUE THREAD

**Issue by ryoto126** [Kotaro7750/eeic-mayfes2020-pkyo#44]

**Comment by ryoto126** [comment]
違うステージの時とかにimportが間に合ってない

**Comment by Kotaro7750** [comment]
game全体のキャッシュは辞書型になっているので、今までのだと新しいステージがloadできていなかった(map1とかの名前になっていたので)。サフィックスとしてステージ名をつけることで回避。それだけだとloadが間に合ってないので、思い切ってload用のSceneをつけて、そこ経由でやることでそれも回避。
